name: vikalp-next
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: pnpm install && pnpm build
  run_command: pnpm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
